const prompts=[
{tool:"Gemini",level:"바로 시작",title:"시설물 안전점검 결과 요약",desc:"긴 점검 메모를 관리자용 핵심 보고로 바꿉니다.",tags:["시설안전","보고서"],text:`너는 시설물 안전관리 업무 담당자야. 아래 정기안전점검 메모를 바탕으로 내부 보고용 요약자료를 작성해줘.\n\n[가상 점검 메모]\n- 대상: 가온대교(가상), 왕복 4차로 도로교량\n- 점검일: 2026년 8월 27일, 날씨 맑음\n- 교량 상판: 3번 경간 바닥판 하면에 폭 0.2mm 내외의 균열 2개 관찰. 길이는 각각 약 0.8m, 1.1m\n- 배수시설: 우측 2번 배수구에 토사와 낙엽이 쌓여 배수가 원활하지 않음\n- 신축이음: 교대 A1 구간 고무재 일부 마모 관찰. 주행 시 소음이 있다는 현장 의견 있음\n- 난간 및 표지: 육안상 특이사항 없음\n- 긴급 통제가 필요한 징후는 점검 당시 발견되지 않음\n- 추가 확인: 균열 변화 여부를 이전 점검 사진과 비교하고, 신축이음 상세점검 필요\n\n관리자가 핵심을 빠르게 파악할 수 있도록 ① 주요 점검 결과 ② 위험요인 ③ 조치 필요사항 ④ 담당 부서와 권장 기한을 표로 정리해줘. 확인되지 않은 내용은 추정하지 말고 '확인 필요'라고 표시해줘.`},
{tool:"Gemini",level:"바로 시작",title:"건설현장 안전점검 브리핑",desc:"현장 기록을 1분 브리핑과 체크리스트로 정리합니다.",tags:["건설안전","현장"],text:`너는 건설현장 안전점검 책임자야. 아래 현장 기록을 바탕으로 아침 안전회의에서 사용할 1분 브리핑을 작성해줘.\n\n[가상 현장 기록]\n- 현장: 새빛 복합시설 신축공사(가상), 지상 12층 골조공사 진행 중\n- 오늘 작업: 8층 거푸집 설치, 타워크레인 자재 인양, 1층 자재 반입\n- 기상: 오전 약한 비 예보, 순간풍속 최대 9m/s 예상\n- 어제 확인사항: 8층 남측 개구부 안전난간 중간대 1곳 이탈, 즉시 임시 조치함\n- 이동통로: 1층 동측 통로에 철근 자재가 일부 적치되어 통행 폭이 좁음\n- 인양작업: 신호수 배치 예정이나 작업 전 무전기 상태 확인 필요\n- 보호구: 신규 근로자 3명이 오늘 처음 투입될 예정\n- 기타: 오후에는 레미콘 차량 출입이 집중될 예정\n\n근로자가 바로 이해할 수 있는 쉬운 말로 작성하고, 오늘 반드시 확인할 사항 5개를 체크박스 목록으로 만들어줘. 법적 판단이 필요한 내용은 단정하지 말고 담당자 검토가 필요하다고 밝혀줘.`},
{tool:"Gemini",level:"한 단계 더",title:"안전 관련 민원 답변 초안",desc:"민원 내용을 분류하고 공감하는 답변 초안을 만듭니다.",tags:["민원","소통"],text:`너는 공공기관 민원 담당자야. 아래 민원 내용을 읽고 답변 초안을 작성해줘.\n\n[가상 민원 내용]\n제목: 보행교 바닥 흔들림과 난간 상태를 확인해 주세요\n내용: 어제 저녁 가족과 함께 한빛천 보행교(가상)를 건너는데 중앙 부분에서 평소보다 흔들리는 느낌을 받았습니다. 남쪽 진입부 난간 한 곳도 손으로 잡았을 때 약간 움직이는 것 같았습니다. 정확한 원인은 알 수 없지만 어린이와 주민이 많이 이용하는 곳이라 걱정됩니다. 현장을 확인해 주시고, 점검이나 보수가 필요하다면 진행 상황을 알려주시기 바랍니다.\n참고: 민원인의 이름·전화번호·주소 등 개인정보는 실습을 위해 제거함\n\n답변은 ① 민원 요지 ② 공감과 접수 안내 ③ 확인이 필요한 사실 ④ 후속 조치와 예상 절차 순서로 구성해줘. 기관이 확인하지 않은 사실이나 처리 기한은 임의로 만들지 말고 [담당자 확인 필요]로 표시해줘. 정중하고 명확한 공공기관 문체를 사용해줘.`},
{tool:"Gemini",level:"한 단계 더",title:"안전회의 후속조치 정리",desc:"회의 메모에서 결정사항과 담당 업무를 추출합니다.",tags:["회의","업무정리"],text:`아래 안전관리 회의 메모를 읽고 실행 중심으로 정리해줘.\n\n[가상 안전관리 회의 메모]\n- 회의: 집중호우 대비 시설물 안전관리 점검회의\n- 일시: 2026년 8월 28일 14:00\n- 참석: 시설안전팀, 건설안전팀, 상황관리팀 담당자\n- 시설안전팀: 하천 인접 교량 12개소의 배수구와 사면 상태를 우선 확인하기로 함. 점검 대상 목록은 8월 29일 오전까지 정리\n- 건설안전팀: 굴착공사 현장 중 침수 우려 현장을 선별하되, 세부 선정 기준은 추가 협의 필요\n- 상황관리팀: 기상특보 발효 시 비상연락망을 재확인하고 점검 결과를 공유 폴더에 모으기로 함\n- 결정사항: 현장 사진 파일명은 '시설명_날짜_점검항목' 형식으로 통일\n- 미결사항: 야간 긴급점검 인력 편성안과 차량 지원 범위\n- 다음 회의: 2026년 8월 30일 10:00, 점검 진행 상황 공유\n\n① 결정사항 ② 미결 쟁점 ③ 담당자별 할 일 ④ 완료 목표일 ⑤ 다음 회의에서 확인할 항목을 표로 정리해줘. 원문에 없는 담당자나 날짜는 만들지 말고 '미정'으로 표시해줘. 마지막에는 참석자에게 보낼 5문장 이내의 공지 메일 초안도 작성해줘.`},
{tool:"Flow",level:"도전",title:"시설물 안전 캠페인 영상",desc:"국민 눈높이의 8초 안전 캠페인 장면을 설계합니다.",tags:["영상","캠페인"],text:`8초 길이의 공공 안전 캠페인 영상. 비가 그친 아침, 한국의 현대적인 교량 보행로를 안전점검 전문가가 태블릿으로 꼼꼼히 확인한다. 카메라는 교량 전경에서 점검자의 손과 안전표지로 부드럽게 이동한다. 차분하고 신뢰감 있는 다큐멘터리 스타일, 자연스러운 청록색과 푸른색 톤, 현실적인 조명, 과장된 위험 장면 없음, 화면 속 글자와 로고 없음, 16:9.`},
{tool:"Opal",level:"바로 시작",title:"안전교육 안내문 생성기",desc:"한 번 입력해 이메일·문자·게시판 안내를 만듭니다.",tags:["자동화","안내문"],text:`국토안전관리원 직원이 사용할 수 있는 안전교육 안내문 생성기를 만들어줘.\n\n사용자가 교육명, 대상, 날짜와 시간, 장소, 주요 내용, 준비물을 입력하면 AI가 내용을 정확하고 이해하기 쉽게 정리하고, 최종적으로 이메일용 안내문, 90자 이내 문자메시지, 게시판용 안내문 세 가지를 보여줘.\n\n입력되지 않은 정보는 임의로 만들지 말고 '확인 필요'로 표시해줘. 결과는 실제 업무에서 바로 사용할 수 있도록 정확하고 간결하게 구성해줘.\n\n[한국어 출력 필수 조건]\n- 사용자 입력 항목의 이름과 설명을 모두 한국어로 표시해줘.\n- 앱의 제목, 안내 문구, 결과 항목명과 최종 결과를 모두 자연스러운 한국어로 작성해줘.\n- 입력 내용에 영어가 포함되어 있어도 최종 결과는 한국어로 작성하고 영어 번역문은 함께 표시하지 마.\n- Output 단계에서 생성하는 HTML 문서의 언어를 한국어(lang=\"ko\")로 설정해줘.\n- 결과 하단에 '본 결과는 AI가 작성한 초안이며 담당자의 확인이 필요합니다.'라고 표시해줘.`},
{tool:"Opal",level:"도전",title:"현장 위험요인 조치안 생성기",desc:"현장 관찰 내용을 구조화된 조치 검토안으로 바꿉니다.",tags:["자동화","위험요인"],text:`국토안전관리원 현장 담당자가 사용할 수 있는 위험요인 조치안 생성기를 만들어줘.\n\n사용자가 시설물 종류, 점검 위치, 관찰 내용, 긴급도, 참고 메모를 입력하면 AI가 위험요인을 분류하고 우선순위를 검토해줘. 최종적으로 ① 관찰 내용 요약 ② 추가 확인사항 ③ 조치 검토안 ④ 보고용 3문장 요약을 보여줘.\n\nAI가 법적 판단이나 안전등급을 확정하지 않도록 하고, 모든 결과에 '전문가 검토가 필요한 초안'이라는 안내를 표시해줘.\n\n[한국어 출력 필수 조건]\n- 사용자 입력 항목의 이름과 설명을 모두 한국어로 표시해줘.\n- 앱의 제목, 안내 문구, 결과 항목명과 최종 결과를 모두 자연스러운 한국어로 작성해줘.\n- 입력 내용에 영어가 포함되어 있어도 최종 결과는 한국어로 작성하고 영어 번역문은 함께 표시하지 마.\n- Facility Type은 '시설물 종류', Inspection Location은 '점검 위치', Observation Details는 '관찰 내용', Urgency Level은 '긴급도', Reference Notes는 '참고 메모'로 표시해줘.\n- Output 단계에서 생성하는 HTML 보고서의 언어를 한국어(lang=\"ko\")로 설정해줘.\n- 결과 하단에 '본 결과는 AI가 작성한 초안이며 안전등급 및 조치 여부는 전문가 검토가 필요합니다.'라고 표시해줘.`}
];
const cards=document.querySelector("#cards"),search=document.querySelector("#search"),toast=document.querySelector("#toast");let selected="전체",opened=0;
function esc(value){return value.replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))}
function render(){const q=search.value.trim().toLowerCase(),shown=prompts.filter(p=>(selected==="전체"||p.tool===selected)&&`${p.title} ${p.desc} ${p.tags.join(" ")}`.toLowerCase().includes(q));cards.innerHTML=shown.length?shown.map((p,i)=>`<article class="card ${prompts.indexOf(p)===opened?"open":""}" data-index="${prompts.indexOf(p)}"><button class="summary"><span class="tool-icon ${p.tool.toLowerCase()}">${p.tool==="Gemini"?"✦":p.tool==="Flow"?"✧":"⌘"}</span><span class="card-copy"><span class="meta"><b>${p.tool}</b><i>${p.level}</i></span><strong>${p.title}</strong><small>${p.desc}</small></span><span class="chevron">⌄</span></button><div class="detail"><div class="tags">${p.tags.map(t=>`<span>#${t}</span>`).join("")}</div><pre>${esc(p.text)}</pre><button class="copy">▣ &nbsp; 프롬프트 복사</button></div><span class="index">${String(i+1).padStart(2,"0")}</span></article>`).join(""):`<div class="empty">조건에 맞는 프롬프트가 없습니다.</div>`}
cards.addEventListener("click",async e=>{const card=e.target.closest(".card");if(!card)return;const i=Number(card.dataset.index);if(e.target.closest(".copy")){await navigator.clipboard.writeText(prompts[i].text);toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),1800)}else if(e.target.closest(".summary")){opened=opened===i?-1:i;render()}});
document.querySelector(".tabs").addEventListener("click",e=>{if(e.target.tagName!=="BUTTON")return;document.querySelectorAll(".tabs button").forEach(b=>b.classList.remove("active"));e.target.classList.add("active");selected=e.target.dataset.tool;opened=-1;render()});search.addEventListener("input",render);render();
